stages:
  prepare:
    cmd: python src/data_generator.py
    deps:
      - src/data_generator.py
    outs:
      - data/dataset.csv
  
  train:
    cmd: python src/train_mlflow.py
    deps:
      - src/train_mlflow.py
      - data/dataset.csv
    outs:
      - models/
    metrics:
      - metrics.json:
          cache: false
  
  optimize:
    cmd: python src/hyperparameter_tuning.py
    deps:
      - src/hyperparameter_tuning.py
      - data/dataset.csv
    metrics:
      - hyperparameter_results.json:
          cache: false 