name: ML Model CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/*, release/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint
      
      - name: Run linting checks
        run: |
          black --check src/
          pylint src/ --fail-under=7

  preprocessing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate and preprocess dataset
        run: |
          mkdir -p data
          python src/data_generator.py
      
      - name: Upload dataset artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-data
          path: data/dataset.csv

  training:
    needs: preprocessing
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download processed data
        uses: actions/download-artifact@v2
        with:
          name: processed-data
          path: data
      
      - name: Setup MLflow
        run: |
          mkdir -p mlruns
          mlflow server --host 0.0.0.0 --port 5000 &
          sleep 5
      
      - name: Train model
        run: |
          export MLFLOW_TRACKING_URI=http://localhost:5000
          python src/train_mlflow.py
      
      - name: Upload model artifact
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: |
            models/
            mlruns/

  testing:
    needs: training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov
      
      - name: Download model
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: .
      
      - name: Run tests
        run: |
          mkdir -p tests
          python -m pytest tests/ --cov=src/ --cov-report=term-missing

  deployment:
    needs: testing
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Download model
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: .
      
      - name: Build Docker image
        run: |
          docker build -t mlops-model:latest .
      
      - name: Test Docker deployment
        run: |
          docker run -d -p 5001:5001 mlops-model:latest
          sleep 5
          curl http://localhost:5001/health
      
      - name: Tag release
        run: |
          VERSION=$(date +%Y%m%d_%H%M%S)
          docker tag mlops-model:latest mlops-model:$VERSION 